### Get Weather API
GET http://localhost:3000/flysheets/weather/41.0076/-91.973419
Content-Type: application/json

### Expected Response:
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 497
ETag: W/"1f1-RDuxAcrv4+fsWOk2kpzENYyujhk"
Date: Fri, 28 Jul 2023 04:48:02 GMT
Connection: close

{
  "success": true,
  "data": {
    "coord": {
      "lon": -91.9734,
      "lat": 41.0076
    },
    "weather": [
      {
        "id": 800,
        "main": "Clear",
        "description": "clear sky",
        "icon": "01n"
      }
    ],
    "base": "stations",
    "main": {
      "temp": 300.14,
      "feels_like": 303.15,
      "temp_min": 299.08,
      "temp_max": 301.12,
      "pressure": 1012,
      "humidity": 83
    },
    "visibility": 10000,
    "wind": {
      "speed": 2.06,
      "deg": 170
    },
    "clouds": {
      "all": 0
    },
    "dt": 1690519470,
    "sys": {
      "type": 1,
      "id": 4085,
      "country": "US",
      "sunrise": 1690455526,
      "sunset": 1690507787
    },
    "timezone": -18000,
    "id": 4855967,
    "name": "Fairfield",
    "cod": 200
  }
}

### Expected Response:
HTTP/1.1 201 Created
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 655
ETag: W/"28f-5lKIWthfo3lpFmUVnGBvywUv4i0"
Date: Fri, 28 Jul 2023 16:18:46 GMT
Connection: close

{
  "success": true,
  "data": {
    "rocketTeamName": "Rocket Team 1",
    "flightNumber": 1,
    "tarcTeamNumber": 123,
    "date": "2023-08-05T00:00:00.000Z",
    "timeOfLaunch": "2023-08-05T08:30:00.000Z",
    "location": "Fairfield, IA",
    "elevationOfLaunchSite": 774,
    "weatherConditions": {
      "temperature": 27,
      "humidity": 50,
      "atmosphericPressure": 1013,
      "windSpeedDirection": "NE",
      "maxGustSpeed": 12
    },
    "rocketInformation": {
      "motorUsed": "F39-7",
      "payloadMass": 1.5,
      "liftoffMass": 5.6,
      "parachuteAreaBooster": 10,
      "staticStabilityMargin": 2.5,
      "motorTotalImpulse": 49.7
    },
    "launchInformation": {
      "railLength": 2.4382,
      "preFlightLaunchAngleDirection": "N",
      "tarcAltimeterModel": "PNUT"
    },
    "_id": "64c3ea668c2d82b23a1d5c07",
    "__v": 0
  }
}

###

